#!/usr/bin/env bash
# generate.sh — render a theme manifest into per-app fragments.
# Sourced by theme-set; functions write fragments to stdout.

# manifest_get FILE SECTION KEY -> value (quotes stripped). Empty if absent.
manifest_get() {
  local file=$1 section=$2 key=$3
  awk -v want="[$section]" -v key="$key" '
    $0 == want { ins=1; next }
    /^\[/      { ins=0 }
    ins {
      line=$0
      sub(/[ \t]*#.*$/, "", line)
      keyfield=line
      sub(/[ \t]*=.*$/, "", keyfield)
      gsub(/^[ \t]+|[ \t]+$/, "", keyfield)
      if (keyfield == key) {
        sub(/^[^=]*=[ \t]*/, "", line)
        gsub(/^[ \t]*"|"[ \t]*$/, "", line)
        print line
        exit
      }
    }
  ' "$file"
}

# load_palette MANIFEST -> sets palette role globals
load_palette() {
  local m=$1
  bg=$(manifest_get "$m" palette bg)
  bg_alt=$(manifest_get "$m" palette bg_alt)
  bg_secondary=$(manifest_get "$m" palette bg_secondary)
  bg_overlay=$(manifest_get "$m" palette bg_overlay)
  bg_selection=$(manifest_get "$m" palette bg_selection)
  fg=$(manifest_get "$m" palette fg)
  fg_muted=$(manifest_get "$m" palette fg_muted)
  red=$(manifest_get "$m" palette red)
  orange=$(manifest_get "$m" palette orange)
  yellow=$(manifest_get "$m" palette yellow)
  green=$(manifest_get "$m" palette green)
  aqua=$(manifest_get "$m" palette aqua)
  blue=$(manifest_get "$m" palette blue)
  purple=$(manifest_get "$m" palette purple)
  accent=$(manifest_get "$m" palette accent)
}

gen_borders() {
  cat <<EOF
ACTIVE_COLOR=0xff${accent}
INACTIVE_COLOR=0xff${bg_overlay}
EOF
}

gen_ghostty() {
  local m=$1
  echo "theme = $(manifest_get "$m" native ghostty)"
}

gen_sketchybar() {
  cat <<EOF
#!/usr/bin/env zsh
# generated by theme-set — do not edit
export BAR_COLOR=0xff${bg}
export BAR_BORDER_COLOR=0xff${bg_overlay}
export BG_PRIMARY=0xff${bg_alt}
export BG_SECONDARY=0xff${bg_secondary}
export BG_OVERLAY=0xff${bg_overlay}
export BG_TRANSPARENT=0x00000000
export FG=0xff${fg}
export FG_MUTED=0xff${fg_muted}
export FG_DIM=0x66${fg_muted}
export RED=0xff${red}
export ORANGE=0xff${orange}
export YELLOW=0xff${yellow}
export GREEN=0xff${green}
export AQUA=0xff${aqua}
export BLUE=0xff${blue}
export PURPLE=0xff${purple}
export ACCENT=0xff${accent}
export SPACE_ACTIVE=0xff${yellow}
export SPACE_INACTIVE=0xff${fg_muted}
export BATTERY_OK=0xff${green}
export BATTERY_LOW=0xff${red}
export CPU_BG=0xff${orange}
export CALENDAR=0xff${yellow}
export WIFI=0xff${aqua}
export CLOCK_FG=0xff${yellow}
export WEATHER_FG=0xff${aqua}
export VOLUME_FG=0xff${blue}
export POMODORO_FG=0xff${fg}
EOF
}
