gui:
  theme:
    activeBorderColor:
      - "#7e9cd8"
      - bold
    inactiveBorderColor:
      - "#54546d"
    searchingActiveBorderColor:
      - "#e6c384"
      - bold
    optionsTextColor:
      - "#7e9cd8"
    selectedLineBgColor:
      - "#2d4f67"
    cherryPickedCommitBgColor:
      - "#54546d"
    cherryPickedCommitFgColor:
      - "#e6c384"
    markedBaseCommitBgColor:
      - "#54546d"
    markedBaseCommitFgColor:
      - "#e46876"
    unstagedChangesColor:
      - "#e46876"
    defaultFgColor:
      - "#dcd7ba"
  authorColors:
    "*": "#d27e99"
  nerdFontsVersion: "3"
