add_newline = false
palette = "gruvbox-material"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$kubernetes\
$golang\
$nodejs\
$cmd_duration\
$fill\
$time\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "bold blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[󰜴](bold yellow)"
error_symbol = "[󰜴](bold red)"
vicmd_symbol = "[󰜴](bold green)"

[git_branch]
symbol = " "
format = 'on [$symbol$branch(:$remote_branch)]($style) '
style = "bold purple"
truncation_length = 20
truncation_symbol = "..."

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "aqua"
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"

[golang]
symbol = " "
style = "bold blue"
format = "[$symbol($version) ]($style)"

[nodejs]
symbol = "⬢ "
style = "bold green"
format = "[$symbol($version) ]($style)"

[docker_context]
symbol = " "
style = "blue dimmed"

[kubernetes]
symbol = "⎈ "
disabled = false
style = "aqua"
format = 'on [$symbol$context( \($namespace\))]($style) '

[[kubernetes.contexts]]
context_pattern = ".*ProdEKS.*"
context_alias = "prod"
style = "bold red"

[[kubernetes.contexts]]
context_pattern = ".*DevEKS.*"
context_alias = "dev"
style = "bold green"

[cmd_duration]
min_time = 2_000
style = "bold yellow"
format = "took [$duration]($style) "

[time]
disabled = false
style = "bold yellow"
format = "[$time]($style)"
time_format = "%H:%M"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[aws]
disabled = true

[package]
disabled = true

[palettes.gruvbox-material]
blue   = "#7daea3"
yellow = "#d8a657"
red    = "#ea6962"
green  = "#a9b665"
purple = "#d3869b"
aqua   = "#89b482"

[palettes.tokyo-night]
blue   = "#7aa2f7"
yellow = "#e0af68"
red    = "#f7768e"
green  = "#9ece6a"
purple = "#bb9af7"
aqua   = "#7dcfff"
