add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$kubernetes\
$golang\
$nodejs\
$cmd_duration\
$fill\
$time\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "bold #7daea3"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[󰜴](bold #d8a657)"
error_symbol = "[󰜴](bold #ea6962)"
vicmd_symbol = "[󰜴](bold #a9b665)"

[git_branch]
symbol = " "
format = 'on [$symbol$branch(:$remote_branch)]($style) '
style = "bold #d3869b"
truncation_length = 20
truncation_symbol = "..."

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#89b482"
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"

[git_metrics]
disabled = false
added_style = "bold #a9b665"
deleted_style = "bold #ea6962"

[golang]
symbol = " "
style = "bold #7daea3"
format = "[$symbol($version) ]($style)"

[nodejs]
symbol = "⬢ "
style = "bold #a9b665"
format = "[$symbol($version) ]($style)"

[docker_context]
symbol = " "
style = "#7daea3 dimmed"

[kubernetes]
symbol = "⎈ "
disabled = false
style = "#89b482"
format = 'on [$symbol$context( \($namespace\))]($style) '

[[kubernetes.contexts]]
context_pattern = ".*ProdEKS.*"
context_alias = "prod"
style = "bold #ea6962"

[[kubernetes.contexts]]
context_pattern = ".*DevEKS.*"
context_alias = "dev"
style = "bold #a9b665"

[cmd_duration]
min_time = 2_000
style = "bold #d8a657"
format = "took [$duration]($style) "

[time]
disabled = false
style = "bold #d8a657"
format = "[$time]($style)"
time_format = "%H:%M"

[jobs]
symbol = ""
style = "bold #ea6962"
number_threshold = 1
format = "[$symbol]($style)"

[aws]
disabled = true

[package]
disabled = true
