#!/usr/bin/env bash
# JankyBorders — Gruvbox Material Dark accents
# Docs: https://github.com/FelixKratz/JankyBorders

borders \
  style=square \
  width=3.0 \
  hidpi=on \
  active_color=0xffe78a4e \
  inactive_color=0xff504945 \
  background_color=0x00000000 &
