#!/usr/bin/env bash
# JankyBorders — Kanagawa Wave accents
# Docs: https://github.com/FelixKratz/JankyBorders

borders \
  style=round \
  width=2.0 \
  hidpi=on \
  active_color=0xff7e9cd8 \
  inactive_color=0xff54546d \
  background_color=0x00000000 &
