# Carga TPM
set-option -g automatic-rename

# Tested options for TMUX compatibility
set -g @plugin 'tmux-plugins/tmux-sensible'

# Clipboard management
set -g @plugin 'tmux-plugins/tmux-yank'

# Tmux Navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

# Tmux Resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Which Key
set -g @plugin 'alexwforsythe/tmux-which-key'

# Catppuccin
set -g @plugin 'catppuccin/tmux'

# Floating window
bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  # open in the same directory of the current pane
  display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}


# Tema Catpuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_default_text "#{b:pane_current_path}"
set -g @catppuccin_window_default_text "#W (#{b:pane_current_path})"
set -g @catppuccin_window_text "#W (#{b:pane_current_path})"
set -g @catppuccin_window_current_text "#W (#{b:pane_current_path})"
run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g status-style "bg=default"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g @catppuccin_date_time_text " %H:%M"
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}" 
set -ag status-right "#{E:@catppuccin_status_date_time}"



# --- terminal & key handling ---
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

set -g extended-keys always
set -g extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'

# Modo vim
set -g mode-keys vi
if-shell 'uname | grep -q Darwin' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip"'

# Keymaps
unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"

# Mouse support
set -g mouse on

# Status bar position
set -g status-position top

# Kill all sessions except current
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

# Fix index
set -g base-index 1
setw -g pane-base-index 1

# TPM init
run '~/.tmux/plugins/tpm/tpm'
set-option -g default-shell /opt/homebrew/bin/fish

set -g set-clipboard on
set -ga terminal-overrides ',*:Ms=\E]52;%p1%s;%p2%s\007'
