# Carga TPM
set-option -g automatic-rename

# Tested options for TMUX compatibility
set -g @plugin 'tmux-plugins/tmux-sensible'

# Clipboard management
set -g @plugin 'tmux-plugins/tmux-yank'

# Tmux Navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

# Tmux Resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Which Key
set -g @plugin 'alexwforsythe/tmux-which-key'

# Floating window
bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  # open in the same directory of the current pane
  display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}


# === Gruvbox Material Dark ===
set -g status-style "bg=#282828,fg=#d4be98"
set -g status-left-length 40
set -g status-right-length 80

set -g status-left "#[bg=#ea6962,fg=#282828,bold] #S #[bg=#282828,fg=#ea6962] "
set -g status-right "#[fg=#e78a4e]│ #[fg=#d8a657]%a %d %b #[fg=#a89984]%H:%M "

set -g window-status-format "#[fg=#a89984] #I:#W "
set -g window-status-current-format "#[bg=#e78a4e,fg=#282828,bold] #I:#W "

set -g pane-active-border-style "fg=#ea6962"
set -g pane-border-style "fg=#504945"

set -g message-style "bg=#504945,fg=#d4be98"
set -g mode-style "bg=#d8a657,fg=#282828"



# --- terminal & key handling ---
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

set -g extended-keys always
set -g extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'

# Modo vim
set -g mode-keys vi
if-shell 'uname | grep -q Darwin' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip"'

# Keymaps
unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"

# Mouse support
set -g mouse on

# Status bar position
set -g status-position top

# Kill all sessions except current
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

# Fix index
set -g base-index 1
setw -g pane-base-index 1

# TPM init
run '~/.tmux/plugins/tpm/tpm'
set-option -g default-shell /opt/homebrew/bin/fish

set -g set-clipboard on
set -ga terminal-overrides ',*:Ms=\E]52;%p1%s;%p2%s\007'
